[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
upload_speed = 115200
lib_deps =
    nickjgniklu/ESP_TF@2.1.1
    esphome/esp-micro-speech-features@1.2.0
    bblanchon/ArduinoJson@^6.21.5
